### ISSUE TITLE
Maintain Language Group when Copying Links

### ISSUE THREAD

**Issue by copperlight** [Netflix/atlas-docs#5]
If you navigate to the following page, and then select Python, you see the Python examples:

https://netflix.github.io/atlas-docs/spectator/timers.html#timer

If you send this link to someone else, the first time they visit it, they will see the Java examples.  This state is remembered in local cookies.

You can specify the language group with a url parameter, as follows:

https://netflix.github.io/atlas-docs/spectator/timers.html?language=python#timer

However this parameter is not maintained when navigating between different pages.

Let's see if we can find a way to maintain a consistent view of a language group when passing around urls.

**Comment by brharrington** [comment]
We aren't using language groups any more.
